Improve patch_pick script
        - try to guess (and confirm) location if target moved
        - add files after succesful merge
        - better success/failure display

diff --git a/bin/patch_pick b/bin/patch_pick
--- a/bin/patch_pick
+++ b/bin/patch_pick
@@ -11,20 +11,40 @@ if [[ $# -eq 3 ]]; then
 fi
 
 if [ ! -f "$TARGETFILE" ]; then
-    echo ERROR: Target does not exist, $TARGETFILE
-    exit
+    echo "Could not find $TARGETFILE"
+
+    TARGETFILE=$(find . -iname `basename $TARGETFILE`)
+
+    echo "Use $TARGETFILE instead?"
+
+    read -n 1 CONTINUE
+
+    if [ "$CONTINUE" == "n" ] || [ "$CONTINUE" == "N" ]; then 
+        echo 
+        echo Cancelling integration...
+        echo
+        exit 1
+    fi
 fi
 
 echo About to patch from:
 echo      sha:  $SHA
 echo      src:  $ORIGFILE
 echo   target:  $TARGETFILE
-echo
-read -p "Are you sure? " -n 1 -r
 echo 
-if [[ $REPLY =~ ^[Yy]$ ]]
-then
-    git diff $SHA~1..$SHA -- $ORIGFILE | patch $TARGETFILE
+
+git diff $SHA~1..$SHA -- $ORIGFILE | patch $TARGETFILE
+
+if [ $? -eq 0 ]; then
+    git add $TARGETFILE
+
+    echo "************************************"
+    echo "       SUCCESSFULLY MERGED          "
+    echo "************************************"
+else
+    echo "************************************"
+    echo "ERROR:  Conflicts, fix them first..."
+    echo "************************************"
 fi
 
 
