Improvements to patch_pick

diff --git a/bin/patch_pick b/bin/patch_pick
--- a/bin/patch_pick
+++ b/bin/patch_pick
@@ -1,21 +1,40 @@
 #!/usr/bin/env bash 
 
-# This script is for cherry-picking between branches when files have moved
-#
-# Usage:
-#     patch_pick SOURCE_SHA FILE_IN_SOURCE_BRANCH [TARGET_FILE]
-#
-#            If no TARGET_FILE specified, it's assumed that the path is the
-#            same as the source branch.  Either way, if the target file cannot
-#            be found, an attempt to find a file with the given name will be made.
-#
-#  If the merge fails, any hunks that could not be applied will be saved in a
-#  TARGET_FILE.rej file to be manually applied.
-# 
-#  I generaly get a list of files that were changed in the source commit, as follows:
-#
-#      git show --name-only SHA
-#
+Usage() {
+
+    cat << EOF
+
+Usage:
+
+    This script is for cherry-picking between branches when files have moved
+
+    $ patch_pick SOURCE_SHA FILE_IN_SOURCE_BRANCH [TARGET_FILE]
+
+        If no TARGET_FILE specified, it's assumed that the path is the
+        same as the source branch.  Either way, if the target file cannot
+        be found, an attempt to find a file with the given name will be made.
+
+    If the merge fails, any hunks that could not be applied will be saved in a
+    TARGET_FILE.rej file to be manually applied.
+ 
+    I generaly get a list of files that were changed in the source commit, as follows:
+
+      git show --name-only SHA
+EOF
+    exit 1
+}
+
+if [[ $# -lt 2 ]] ; then
+    Usage
+fi
+
+if [[ ! -e ".git" ]]; then
+    echo
+    echo "----------------------------------------------------------------"
+    echo "ERROR:  This script must be run from the top level of a git repo"
+    echo "----------------------------------------------------------------"
+    Usage
+fi
 
 SHA=$1
 ORIGFILE=$2
@@ -48,6 +67,7 @@ echo      src:  $ORIGFILE
 echo   target:  $TARGETFILE
 echo 
 
+set -o pipefail
 git diff $SHA~1..$SHA -- $ORIGFILE | patch $TARGETFILE
 
 if [ $? -eq 0 ]; then
